name: nexusdeep
description: "Nexus Deep is a bridge connecting Ethiopian diaspora investors with the homeland's promising ventures."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  dio: ^5.4.0
  intl: ^0.19.0
  flutter_animate: ^4.4.1
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  file_picker: ^6.1.1
  flutter_carousel_widget: ^2.2.0
  flutter_facebook_auth: ^6.2.0
  flutter_image_compress: ^2.1.0
  flutter_native_splash: ^2.3.9
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.0.2
  flutter_webrtc: ^0.9.47
  fluttertoast: ^8.2.4
  get: ^4.6.6
  get_it: ^7.6.7
  go_router: ^13.0.1
  http: ^1.2.1
  iconly: ^1.0.1
  image_picker: ^1.0.7
  lottie: ^3.0.0
  mime: ^1.0.5
  overlay_support: ^2.1.0
  path_provider: ^2.1.2
  rxdart: ^0.27.7
  rxdart_ext: ^0.2.9
  rx_shared_preferences: ^3.1.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.5
  timeago: ^3.2.2
  url_launcher: ^6.2.4
  chewie: ^1.7.4
  open_filex: ^4.3.4
  pinput: ^3.0.1
  uuid: ^4.3.3
  envied: ^0.5.3
  provider: ^6.1.1
  readmore: ^2.2.0
  cached_network_image: ^3.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mocktail: ^1.0.0
  bloc_test: ^9.1.4
  very_good_analysis: ^5.0.0+1
  google_sign_in_mocks: ^0.3.0
  envied_generator: ^0.5.3
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/vectors/
    - assets/icons/
